# Generated by Django 3.1.6 on 2021-02-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('total', models.IntegerField(max_length=100)),
            ],
        ),
    ]
