# Generated by Django 3.1.6 on 2021-02-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='total',
            field=models.CharField(max_length=100),
        ),
    ]
