# Generated by Django 3.1.6 on 2021-02-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_auto_20210216_0639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
